### ISSUE TITLE
Was elemental filtering applied to the starting datasets?

### ISSUE THREAD

**Issue by sgbaird** [txie-93/cdvae#11]
E.g. don't include noble gases, don't include radioactive elements. Went through the manuscript and had trouble finding if/where this was clarified.

**Comment by sgbaird** [comment]
Considering in the context of:
- https://github.com/sparks-baird/mp-time-split/pull/34

**Comment by sgbaird** [comment]
It seems like probably no element filtering (at least not filtering out the radioactive elements) in [MP-20](https://github.com/txie-93/cdvae/tree/main/data/mp_20) in that there are 89 unique elements represented.

**Comment by txie-93** [comment]
Thanks, @sgbaird. You are correct. There is no filtering.
