### ISSUE TITLE
What code was used to visualize the structures?

### ISSUE THREAD

**Issue by sgbaird** [txie-93/cdvae#12]
It looks a lot like `pymatviz` (see [`struct_vis`](https://github.com/janosh/pymatviz#structure)), but I didn't think that `pymatviz` dealt with transparency, so I'm assuming it's something else.

https://github.com/txie-93/cdvae/tree/main/data/perov_5#visualization-of-structures

**Comment by txie-93** [comment]
We used this: https://wiki.fysik.dtu.dk/ase/ase/visualize/visualize.html

**Comment by sgbaird** [comment]
Ah, great! Thank you. I've used the interactive functions before but not the static ones, so didn't recognize them at first. Thanks!
