### ISSUE TITLE
How to train prop_models on a custom dataset

### ISSUE THREAD

**Issue by Breaddsmall** [txie-93/cdvae#33]
I really appreciate your work and I want to train and evaluate this model on a custom dataset. However, after completing the three tasks, I failed to evaluate the generation task and optimisation task. It seems that I need to train another property predictor (like those models in `cdvae/prop_models`) on the custom dataset independently, but I failed find the code to train it. Would you mind provide some instructions to train this property predictor? Thank you very much!

**Comment by kyonofx** [comment]
Thanks for your interest. You can use the argument `python run.py <other config> model=supervise` to train property predictors. The config is here:

https://github.com/txie-93/cdvae/blob/main/conf/model/supervise.yaml

**Comment by Breaddsmall** [comment]
Thank you!
