### ISSUE TITLE
Decoder loss

### ISSUE THREAD

**Issue by filipekstrm** [txie-93/cdvae#7]
Hi,

Very interesting work! A question, though: in the paper equation 2 (the decoder loss) shouldn’t the score, s, be divided by sigma (i.e., so that it becomes the score conditioned on sigma), and d_min be divided by sigma^2 (instead of just sigma)? This is what I get from comparing the work by Song and Ermon, and it also seems to be how you have implemented it here in the codebase. Or maybe I have misunderstood something?

**Comment by txie-93** [comment]
Great question. If you look at Eq 6 from Song and Ermon's paper, the \lambda(\sigma_i) = \sigma_i^2. Also, they reparameterize s(x, \sigma) = s(x) / \sigma. We factor both into our equation to make it shorter. It should be the same as Song and Ermon's equation.

**Comment by filipekstrm** [comment]
Ah right, for some reason I didn't realize that you in your paper had simplified away \lambda(\sigma). Then it is indeed the same expression! My bad!
