### ISSUE TITLE
Question about the reconstruction task

### ISSUE THREAD

**Issue by lyzustc** [txie-93/cdvae#8]
Hi authors,

I have a question about the reconstruction experiments in CDVAE. I have tried running the training on mp_20 dataset, and run these commands to do the reconstruction and evaluation following instructions in README.md:

```
python scripts/evaluate.py --model_path /home/lyz/cdvae/hydra/singlerun/2022-04-04/mp_20/ --tasks recon
python scripts/compute_metrics.py --root_path /home/lyz/cdvae/hydra/singlerun/2022-04-04/mp_20/ --tasks recon
```

However, the reconstruction match rate is very low:

```
{"match_rate": 0.16604023877957108, "rms_dist": 0.05085572933343641}
```

I noticed that there is an option to only reconstruct coordinates and lattices while keeping ground truth atom types and numbers, and tried this option as:

```
python scripts/evaluate.py --model_path /home/lyz/cdvae/hydra/singlerun/2022-04-04/mp_20/ --tasks recon --force_num_atoms --force_atom_types
```

This time the reconstruction match rate is much higher:

```
{"match_rate": 0.3720981649347778, "rms_dist": 0.14127310664427778}
```

Hence I think whether two materials match is related to their atom types. I am wondering for the reconstruction performance result reported in Table 1 of the paper, do you reconstruct all things about materials in the test set, or only reconstruct coordinates and lattices and keeping ground truth atom types and numbers?

Thank you for your possible help!

Best

**Comment by txie-93** [comment]
Hi @lyzustc, thank you for your question. No, we didn't use `--force_num_atoms` or `--force_atom_types` flags. The match_rate you got is quite low. What is your `val_coord_loss`? You should get at least 0.71 - 0.75 at the end of the training.

**Comment by lyzustc** [comment]
Hi @txie-93, thank you for the response! I found that during the training, the instablity issue #5 happens so the training stops at epoch 89, and the val-coord_loss is 0.86 - 0.88. How many epochs do we need to make training converge? 

As for the reconstruction evaluation, the StructureMatcher API from pymatgen library is used to match two materials. I am curious that to make two materials matched, whether the atom type composition of them must be the same (i.e., having exactly the same element set and the same number of atoms for each element)? If the answer is no, I am also wondering how atoms of two materials with different compositions are matched to compute coordinate RMSE.

Thank you for your possible help!

Best

**Comment by sgbaird** [comment]
> As for the reconstruction evaluation, the StructureMatcher API from pymatgen library is used to match two materials. I am curious that to make two materials matched, whether the atom type composition of them must be the same (i.e., having exactly the same element set and the same number of atoms for each element)? If the answer is no, I am also wondering how atoms of two materials with different compositions are matched to compute coordinate RMSE.

@lyzustc see Appendix G of the [manuscript](https://arxiv.org/abs/2110.06197):
> We note several points on why we define the metrics in their current forms. 1) COV requires both structure and composition distances to be within the thresholds, because generating materials that are structurally close to one ground truth material and compositionally close to another is not meaningful. As a result, AMSD and AMCD are less useful than COV. 2) We use fingerprint distance, rather than RMSE from StructureMatcher (Ong et al., 2013), because the material space is too large for the models to generate enough materials to exactly match the ground truth materials. StructureMatcher first requires the compositions of two materials to exactly match, which will cause all models to have close-to-zero coverage.

**Comment by lyzustc** [comment]
@sgbaird Thank you for your information!
